name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - beta

jobs:
  build_and_deploy_main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy Main
    steps:
      - uses: actions/checkout@v4

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"

  build_and_deploy_beta:
    if: github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    name: Deploy Beta
    steps:
      - uses: actions/checkout@v4

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BETA }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"
